// message loading
export const NEW_MESSAGE = 'NEW_MESSAGE'
export const SET_LOADING = 'SET_LOADING'

// menu
export const ADD_MENU = 'ADD_MENU'
export const REMOVE_MENU ='REMOVE_MENU'
export const SWITCH_MENU ='SWITCH_MENU'


// supplier
export const RECEIVE_PROVIDERS ='RECEIVE_PROVIDERS'
export const UPDATE_PROVIDER ='UPDATE_PROVIDER'
export const RECEIVE_SORTNAME ='RECEIVE_SORTNAME'

export const RECEIVE_ALL_CATEGORY ='RECEIVE_ALL_CATEGORY'


// goodsMgmt
export const RECEIVE_ALL_GOODS ='RECEIVE_ALL_GOODS'
export const RECEIVE_OPER_GOODS ='RECEIVE_OPER_GOODS'
export const SET_SELECT_TREE ='SET_SELECT_TREE'

// matchSupplier
export const RECEIVE_PARENT_AREA ='RECEIVE_PARENT_AREA'
export const RECEIVE_CHILD_AREA ='RECEIVE_CHILD_AREA'
export const SELECT_PARENT_AREA ='SELECT_PARENT_AREA'
export const RECEIVE_ALL_HOUSES ='RECEIVE_ALL_HOUSES'
export const RECEIVE_MATCH_PROVIDERS ='RECEIVE_MATCH_PROVIDERS'
export const SET_MATCH_PROVIDERS_FILTER ='SET_MATCH_PROVIDERS_FILTER'

// solution
export const RECEIVE_STANDARD_SOLUTION ='RECEIVE_STANDARD_SOLUTION'

// createPlan 
export const RECEIVE_ORDERS_PLAN_DETAIL ='RECEIVE_ORDERS_PLAN_DETAIL'
export const UPDATE_ROOM_LIST ='UPDATE_ROOM_LIST'
export const CLEAR_PLAN_DETAIL ='CLEAR_PLAN_DETAIL'

// work order
export const RECEIVE_WORK_ORDER ='RECEIVE_WORK_ORDER'
export const RECEIVE_ORDER_INFO ='RECEIVE_ORDER_INFO'

// project delivery
export const RECEIVE_DELIVERY_ORDER ='RECEIVE_DELIVERY_ORDER'


// goodsDetail
export const RECEIVE_GOODS_DETAIL ='RECEIVE_GOODS_DETAIL'
export const RECEIVE_GOODS_PRO ='RECEIVE_GOODS_PRO'

//order
export const RECEIVE_ORDER_ORDERS ='RECEIVE_ORDER_ORDERS'
export const RECEIVE_ORDER_DETAIL ='RECEIVE_ORDER_DETAIL'
export const RECEIVE_ORDERS_DETAIL ='RECEIVE_ORDERS_DETAIL'
export const RECEIVE_NEW_ORDERS_DETAIL = 'RECEIVE_NEW_ORDERS_DETAIL'
export const RECEIVE_NEW_ORDERS_PLAN_DETAIL = 'RECEIVE_NEW_ORDERS_PLAN_DETAIL'
export const UPDATE_NEW_ROOM_LIST = 'UPDATE_NEW_ROOM_LIST'
export const CLEAR_NEW_PLAN_DETAIL = 'CLEAR_NEW_PLAN_DETAIL'
export const NEW_ORDER_INITPAGE ='NEW_ORDER_INITPAGE'

//measure query
export const RECEIVE_MEASURE_ORDERS ='RECEIVE_MEASURE_ORDERS'


//measure add | get
export const GET_MEASURE_HOUSEMEASURE ='GET_MEASURE_HOUSEMEASURE'
export const GET_MEASURE_HOUSEMSG ='GET_MEASURE_HOUSEMSG'
export const GET_MEASURE_HOUSEPROPERTY ='GET_MEASURE_HOUSEPROPERTY'
export const GET_MEASURE_HOUSEPIC ='GET_MEASURE_HOUSEPIC'

export const SET_MEASURE_HOUSEMEASURE ='SET_MEASURE_HOUSEMEASURE'
export const SET_MEASURE_HOUSEMSG ='SET_MEASURE_HOUSEMSG'
export const SET_MEASURE_HOUSEPROPERTY ='SET_MEASURE_HOUSEPROPERTY'
export const SET_MEASURE_HOUSEPIC ='SET_MEASURE_HOUSEPIC'
